

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Encabezado con CSS</title>
    <link rel="stylesheet" href="../css/css.css">
    
    
</head>
<body>
    
    <header>
        <h1>VENTA DE AUTOS</h1>
        <ul>
        <li>Pagina principal</li>
            <li>Administración</li>
        </ul>
    </header>

 <section></section>
    

