<h1>CATÁLOGO</h1>
<form method="GET" action="router.php">
    <input type="hidden" name="action" value="buscar"> <!-- Campo oculto para la acción -->
    <label for="atributo">Buscar por:</label>
    <select id="atributo" name="atributo" required>
        <option value="marca">Marca</option>
        <option value="color">Color</option>
        <option value="kilometros">Kilómetros</option>
        <option value="asientos">Asientos</option>
        <option value="modelo">Modelo</option>
    </select>

    <label for="valor">Valor:</label>
    <input type="text" id="valor" name="valor" required>

    <button type="submit">Buscar</button>
</form>

