

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catalogo de autos</title>
    <link rel="stylesheet" href="../css/css.css">
    
    
</head>
<body>
    
    <header>
        <h1>VENTA DE AUTOS</h1>
        <ul>
        <li><a href="router.php?/listar">Pagina principal</a></li>
            <li>Administración</li>
        </ul>
    </header>
    <div class="titulo"><h1>Nuestro catalogo completo</h1></div>


    

